ARG UBI_VERSION=9
ARG NODE_VERSION=22
ARG MODULE=--module=nodejs:22

FROM registry.access.redhat.com/ubi${UBI_VERSION} AS ubi-micro-build
ARG MODULE
ARG UBI_VERSION

ADD build-umd-image.sh .
RUN UBI_VERSION=$UBI_VERSION ./build-umd-image.sh ${MODULE} nodejs npm glibc-langpack-en glibc-minimal-langpack

FROM scratch
ENV LANG en_US.UTF-8

LABEL org.opencontainers.image.source="https://github.com/ubi-micro-dev/ubi-micro-dev"
LABEL com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI"
LABEL io.openshift.expose-services=""

COPY --from=ubi-micro-build /mnt/rootfs /
COPY --from=ubi-micro-build /usr/share/buildinfo /

ENTRYPOINT node
WORKDIR /home/ubi-micro-dev
USER 1001
