ARG UBI_VERSION=9
ARG JDK_VERSION=21
ARG JDK_PKG=java-21-openjdk-headless

FROM registry.access.redhat.com/ubi${UBI_VERSION} AS ubi-micro-build
ARG UBI_VERSION
ARG JDK_PKG

ADD build-ubi-micro-dev.sh .
RUN UBI_VERSION=$UBI_VERSION ./build-ubi-micro-dev.sh

RUN dnf --installroot /mnt/rootfs install \
        $JDK_PKG coreutils-single glibc-langpack-en glibc-minimal-langpack \
        --releasever $UBI_VERSION \
        --setopt install_weak_deps=false --nodocs -y

FROM scratch
ENV LANG en_US.UTF-8

LABEL org.opencontainers.image.source="https://github.com/ubi-micro-dev/ubi-micro-dev"

ADD ubi-micro-dev.sh /usr/bin
COPY --from=ubi-micro-build /mnt/rootfs /
COPY --from=ubi-micro-build /etc/yum.repos.d/* /etc/yum.repos.d/

ENTRYPOINT java
WORKDIR /home/ubi-micro-dev
USER 0
